package agent

import (
	"fmt"
	"strings"

	"github.com/this-is-alpha-iota/clyde/agent/mcp"
	"github.com/this-is-alpha-iota/clyde/agent/prompts"
	"github.com/this-is-alpha-iota/clyde/agent/providers"
	"github.com/this-is-alpha-iota/clyde/agent/tools"
	// Blank-import all tool packages so their init() functions register tools
	// into the global registry. This is the ONLY place this import exists —
	// external consumers never need to do it.
	_ "github.com/this-is-alpha-iota/clyde/agent/tools"
)

// Config holds the agent-relevant configuration fields.
// The CLI reads its config file and maps the relevant fields into this struct
// before constructing the agent.
type Config struct {
	// APIKey is the Anthropic API key (required).
	APIKey string
	// APIURL is the Claude API endpoint URL (e.g. "https://api.anthropic.com/v1/messages").
	APIURL string
	// ModelID is the Claude model identifier (e.g. "claude-opus-4-6").
	ModelID string
	// MaxTokens is the maximum output tokens per API call.
	MaxTokens int
	// ContextWindowSize is the model's context window in tokens (for diagnostic display).
	ContextWindowSize int
	// ThinkingBudget configures extended thinking. 0 = adaptive (default), >0 = manual budget.
	ThinkingBudget int
	// NoThink disables extended thinking entirely when true.
	NoThink bool
	// BraveSearchAPIKey is the optional Brave Search API key for the web_search tool.
	BraveSearchAPIKey string
	// MCPPlaywright enables Playwright MCP browser automation when true.
	MCPPlaywright bool
	// MCPPlaywrightArgs are extra args for npx @playwright/mcp (e.g. "--headless").
	MCPPlaywrightArgs string
	// ReserveTokens is the number of tokens to reserve for the response.
	// Compaction triggers when input exceeds (ContextWindowSize - ReserveTokens).
	// 0 uses DefaultReserveTokens (16000).
	ReserveTokens int
	// CompactIncludeRecentContext controls whether recent kept messages are fed
	// into compaction phases as extra context. Default true; set false for max token savings.
	CompactIncludeRecentContext *bool
	// ToolResultThreshold is the character count above which tool results are
	// intelligently summarized during compaction. 0 uses DefaultToolResultThreshold (2000).
	ToolResultThreshold int
}

// ProgressCallback receives tool progress lines (the → lines).
// Called unconditionally for every tool execution.
// The toolUseID parameter carries the API's tool_use_id for session persistence.
type ProgressCallback func(message string, toolUseID string)

// OutputCallback receives tool output bodies (full, untruncated text).
// Called unconditionally; the caller is responsible for truncation.
// The toolUseID parameter carries the API's tool_use_id for session persistence.
type OutputCallback func(output string, toolUseID string)

// ThinkingCallback receives thinking trace text from Claude's extended thinking.
// The text is the raw, full thinking content; the caller is responsible for
// truncation and styling. The signature is the API's cryptographic token needed
// for round-tripping thinking blocks in conversation history.
type ThinkingCallback func(text string, signature string)

// DiagnosticCallback receives diagnostic information (cache stats, token counts, etc.).
// Called unconditionally; the caller decides whether to display.
type DiagnosticCallback func(message string)

// SpinnerCallback receives signals to start or stop the loading spinner.
// When start is true, message contains the operation text to display.
// When start is false, message is empty and the spinner should stop.
// Called unconditionally; the caller decides whether to act.
type SpinnerCallback func(start bool, message string)

// ErrorCallback receives errors during processing (optional, for logging)
type ErrorCallback func(err error)

// UserMessageCallback is called when a user message is added to the conversation.
// Used by the session layer to persist user messages to disk.
type UserMessageCallback func(text string)

// AssistantMessageCallback is called when an assistant text response is received.
// Used by the session layer to persist assistant messages to disk.
type AssistantMessageCallback func(text string)

// ToolUseCallback is called when a tool_use block is generated by the API.
// It provides the full metadata needed for session persistence and reconstruction:
// displayMsg is the human-readable progress line, toolName is the API tool name,
// toolUseID is the unique ID, and input is the tool's input parameters.
type ToolUseCallback func(displayMsg string, toolName string, toolUseID string, input map[string]interface{})

// Agent handles conversation and tool execution
type Agent struct {
	apiClient          *providers.Client
	systemPrompt       string
	history            []providers.Message
	progressCallback   ProgressCallback
	outputCallback     OutputCallback
	thinkingCallback   ThinkingCallback
	diagnosticCallback DiagnosticCallback
	spinnerCallback    SpinnerCallback
	errorCallback      ErrorCallback
	userMsgCallback    UserMessageCallback
	assistantMsgCallback AssistantMessageCallback
	toolUseCallback      ToolUseCallback
	compactionCallback CompactionCallback
	lastUsage          providers.Usage // Token usage from the most recent API response
	contextWindowSize  int             // Model context window size in tokens (for diagnostic display)
	reserveTokens      int             // Tokens to reserve for response; triggers compaction when exceeded
	compactIncludeRecentContext bool   // Feed recent kept messages into compaction phases
	toolResultThreshold        int    // Char threshold for intelligent tool-result summarization
	mcpServer          *mcp.PlaywrightServer // MCP server (nil if not enabled)
}

// AgentOption is a functional option for configuring an Agent
type AgentOption func(*Agent)

// WithProgressCallback sets the callback for tool progress lines (→ lines).
func WithProgressCallback(cb ProgressCallback) AgentOption {
	return func(a *Agent) {
		a.progressCallback = cb
	}
}

// WithOutputCallback sets the callback for tool output bodies (full text).
func WithOutputCallback(cb OutputCallback) AgentOption {
	return func(a *Agent) {
		a.outputCallback = cb
	}
}

// WithThinkingCallback sets the callback for thinking trace display.
// The callback receives the full, untruncated thinking text.
func WithThinkingCallback(cb ThinkingCallback) AgentOption {
	return func(a *Agent) {
		a.thinkingCallback = cb
	}
}

// WithDiagnosticCallback sets the callback for diagnostic messages
// (cache stats, token counts, redacted thinking notes, etc.).
func WithDiagnosticCallback(cb DiagnosticCallback) AgentOption {
	return func(a *Agent) {
		a.diagnosticCallback = cb
	}
}

// WithSpinnerCallback sets the spinner callback for starting/stopping
// the loading spinner during operations.
func WithSpinnerCallback(cb SpinnerCallback) AgentOption {
	return func(a *Agent) {
		a.spinnerCallback = cb
	}
}

// WithErrorCallback sets the error callback
func WithErrorCallback(cb ErrorCallback) AgentOption {
	return func(a *Agent) {
		a.errorCallback = cb
	}
}

// WithUserMessageCallback sets the callback for user messages.
// Called once per HandleMessage invocation with the user's input text.
func WithUserMessageCallback(cb UserMessageCallback) AgentOption {
	return func(a *Agent) {
		a.userMsgCallback = cb
	}
}

// WithAssistantMessageCallback sets the callback for assistant text responses.
// Called once per HandleMessage invocation with the final text response.
func WithAssistantMessageCallback(cb AssistantMessageCallback) AgentOption {
	return func(a *Agent) {
		a.assistantMsgCallback = cb
	}
}

// WithToolUseCallback sets the callback for tool_use block metadata.
// Called once per tool_use block with the display message, tool name,
// tool use ID, and input parameters.
func WithToolUseCallback(cb ToolUseCallback) AgentOption {
	return func(a *Agent) {
		a.toolUseCallback = cb
	}
}

// WithContextWindowSize sets the model's context window size in tokens.
// This is used for diagnostic display to show context usage percentage,
// and for compaction threshold calculation.
func WithContextWindowSize(size int) AgentOption {
	return func(a *Agent) {
		a.contextWindowSize = size
	}
}

// WithReserveTokens sets the number of tokens to reserve for the agent's
// response. Compaction is triggered when input tokens exceed
// (contextWindowSize - reserveTokens). Default is DefaultReserveTokens (16000).
func WithReserveTokens(tokens int) AgentOption {
	return func(a *Agent) {
		a.reserveTokens = tokens
	}
}

// New creates a new Agent from a Config. This is the primary public
// constructor. It internally:
//   - Creates the API client (with optional thinking configuration)
//   - Loads the system prompt
//   - Sets up MCP Playwright tools if configured
//
// The caller only needs to import the agent package — no need to import
// providers, tools, config, or prompts.
func New(cfg Config, opts ...AgentOption) *Agent {
	// Create API client
	client := providers.NewClient(cfg.APIKey, cfg.APIURL, cfg.ModelID, cfg.MaxTokens)

	// Configure thinking
	if !cfg.NoThink {
		thinking := &providers.ThinkingConfig{
			Type: "adaptive",
		}
		if cfg.ThinkingBudget > 0 {
			thinking = &providers.ThinkingConfig{
				Type:         "enabled",
				BudgetTokens: cfg.ThinkingBudget,
			}
		}
		client = client.WithThinking(thinking)
	}

	// Tool registration is handled by the blank import of agent/tools above,
	// which triggers init() functions in each tool file. No action needed here.

	// Determine compactIncludeRecentContext — default true unless explicitly set false
	includeRecent := true
	if cfg.CompactIncludeRecentContext != nil {
		includeRecent = *cfg.CompactIncludeRecentContext
	}

	a := &Agent{
		apiClient:                  client,
		systemPrompt:               prompts.SystemPrompt,
		history:                    []providers.Message{},
		contextWindowSize:          cfg.ContextWindowSize,
		reserveTokens:              cfg.ReserveTokens,
		compactIncludeRecentContext: includeRecent,
		toolResultThreshold:        cfg.ToolResultThreshold,
	}

	// Apply functional options
	for _, opt := range opts {
		opt(a)
	}

	// Setup Playwright MCP if configured
	if cfg.MCPPlaywright {
		server := mcp.NewPlaywrightServer(cfg.MCPPlaywrightArgs)
		if err := mcp.RegisterPlaywrightTools(server); err != nil {
			if a.errorCallback != nil {
				a.errorCallback(fmt.Errorf("failed to register Playwright MCP tools: %w", err))
			}
		} else {
			a.mcpServer = server
		}
	}

	return a
}

// NewAgent creates a new agent with an explicit API client and system prompt.
// This is a lower-level constructor primarily for tests and advanced library
// consumers who need full control over the client and prompt. For typical
// usage, prefer New(cfg, ...opts).
func NewAgent(apiClient *providers.Client, systemPrompt string, opts ...AgentOption) *Agent {
	agent := &Agent{
		apiClient:    apiClient,
		systemPrompt: systemPrompt,
		history:      []providers.Message{},
	}

	// Apply options
	for _, opt := range opts {
		opt(agent)
	}

	return agent
}

// Close releases resources owned by the agent (e.g. MCP server subprocess).
// It is safe to call multiple times. If the agent was created without MCP,
// Close is a no-op.
func (a *Agent) Close() error {
	if a.mcpServer != nil {
		return a.mcpServer.Close()
	}
	return nil
}

// Usage is re-exported from providers for use by external consumers
// who should not need to import agent/providers directly.
type Usage = providers.Usage

// LastUsage returns the token usage from the most recent API response.
// Returns a zero-value Usage if no API call has been made yet.
func (a *Agent) LastUsage() Usage {
	return a.lastUsage
}

// HandleMessage processes a user message and returns the response
func (a *Agent) HandleMessage(userInput string) (string, error) {
	// Add user message to history
	a.history = append(a.history, providers.Message{
		Role:    "user",
		Content: userInput,
	})

	// Emit user message callback for session persistence
	if a.userMsgCallback != nil {
		a.userMsgCallback(userInput)
	}

	// Get all registered tools
	allTools := tools.GetAllTools()

	// Conversation loop - continue until we get a text response
	for {
		// Check compaction threshold before API call.
		// If input tokens have exceeded (contextWindowSize - reserveTokens),
		// compact the history to free up context space.
		if a.ShouldCompact() {
			if err := a.Compact(); err != nil {
				if a.errorCallback != nil {
					a.errorCallback(fmt.Errorf("compaction failed: %w", err))
				}
				// Continue without compaction — better to try with full context
				// than to fail entirely
			}
		}

		// Start spinner while waiting for API response
		if a.spinnerCallback != nil {
			a.spinnerCallback(true, "Thinking...")
		}

		resp, err := a.apiClient.Call(a.systemPrompt, a.history, allTools)

		// Stop spinner once API responds
		if a.spinnerCallback != nil {
			a.spinnerCallback(false, "")
		}

		if err != nil {
			return fmt.Sprintf("Error: %v", err), err
		}

		// Store usage for context tracking
		a.lastUsage = resp.Usage

		// Emit cache and diagnostic information unconditionally.
		// The CLI layer filters based on its own log level.
		if resp.Usage.CacheReadInputTokens > 0 && a.diagnosticCallback != nil {
			totalInputTokens := resp.Usage.InputTokens + resp.Usage.CacheReadInputTokens

			// Cache token fraction
			a.diagnosticCallback(fmt.Sprintf("💾 Cache: %d/%d tokens",
				resp.Usage.CacheReadInputTokens, totalInputTokens))

			// Detailed cache info with creation tokens and context %
			detail := fmt.Sprintf("💾 Cache: %d/%d tokens | Creation: %d tokens",
				resp.Usage.CacheReadInputTokens, totalInputTokens,
				resp.Usage.CacheCreationInputTokens)
			if a.contextWindowSize > 0 {
				pct := (totalInputTokens * 100) / a.contextWindowSize
				if pct > 100 {
					pct = 100
				}
				detail += fmt.Sprintf(" | Context: %d%% (%d/%d)",
					pct, totalInputTokens, a.contextWindowSize)
			}
			a.diagnosticCallback(detail)
		}

		// Token usage diagnostics
		if a.diagnosticCallback != nil {
			a.diagnosticCallback(fmt.Sprintf("🔍 Tokens: input=%d output=%d cache_read=%d cache_create=%d",
				resp.Usage.InputTokens, resp.Usage.OutputTokens,
				resp.Usage.CacheReadInputTokens, resp.Usage.CacheCreationInputTokens))
		}

		var assistantContent []providers.ContentBlock
		var textResponses []string
		var toolUseBlocks []providers.ContentBlock

		for _, block := range resp.Content {
			// Ensure tool_use blocks always have a non-nil Input map.
			if block.Type == "tool_use" && block.Input == nil {
				block.Input = map[string]interface{}{}
			}
			assistantContent = append(assistantContent, block)

			switch block.Type {
			case "text":
				if block.Text != "" {
					textResponses = append(textResponses, block.Text)
				}
			case "tool_use":
				toolUseBlocks = append(toolUseBlocks, block)
			case "thinking":
				// Emit full thinking trace unconditionally
				if block.Thinking != "" && a.thinkingCallback != nil {
					a.thinkingCallback(block.Thinking, block.Signature)
				}
			case "redacted_thinking":
				// Redacted thinking — note it via diagnostics
				if a.diagnosticCallback != nil {
					a.diagnosticCallback("🔒 Redacted thinking block (encrypted by safety system)")
				}
			}
		}

		// Add assistant response to history (includes thinking blocks
		// for proper round-tripping as required by the API)
		a.history = append(a.history, providers.Message{
			Role:    "assistant",
			Content: assistantContent,
		})

		// If no tool use, return text responses
		if len(toolUseBlocks) == 0 {
			response := strings.Join(textResponses, "\n")
			// Emit assistant message callback for session persistence
			if a.assistantMsgCallback != nil && response != "" {
				a.assistantMsgCallback(response)
			}
			return response, nil
		}

		// Execute tools
		var toolResults []providers.ContentBlock
		var pendingImages []providers.ContentBlock

		for _, toolBlock := range toolUseBlocks {
			reg, err := tools.GetTool(toolBlock.Name)
			if err != nil {
				// Unknown tool
				toolResults = append(toolResults, providers.ContentBlock{
					Type:      "tool_result",
					ToolUseID: toolBlock.ID,
					Content:   err.Error(),
					IsError:   true,
				})
				continue
			}

			// Emit progress message unconditionally (the → lines)
			if reg.Display != nil && a.progressCallback != nil {
				displayMsg := reg.Display(toolBlock.Input)
				if displayMsg != "" {
					a.progressCallback(displayMsg, toolBlock.ID)
				}
			}

			// Emit tool_use metadata for session persistence
			if a.toolUseCallback != nil {
				displayMsg := ""
				if reg.Display != nil {
					displayMsg = reg.Display(toolBlock.Input)
				}
				a.toolUseCallback(displayMsg, toolBlock.Name, toolBlock.ID, toolBlock.Input)
			}

			// Execute the tool
			output, err := reg.Execute(toolBlock.Input, a.apiClient, a.history)

			var resultContent string
			var isError bool
			if err != nil {
				resultContent = err.Error()
				isError = true
			} else {
				resultContent = output
				isError = false

				// Check for IMAGE_LOADED marker
				if strings.HasPrefix(output, "IMAGE_LOADED:") {
					// Parse: IMAGE_LOADED:<media_type>:<size_kb>:<base64_data>
					parts := strings.SplitN(output, ":", 4)
					if len(parts) == 4 {
						mediaType := parts[1]
						sizeKB := parts[2]
						imageData := parts[3]

						// Store image for inclusion in this turn's response
						pendingImages = append(pendingImages, providers.ContentBlock{
							Type: "image",
							Source: &providers.ImageSource{
								Type:      "base64",
								MediaType: mediaType,
								Data:      imageData,
							},
						})

						// Update result content to confirmation message
						resultContent = fmt.Sprintf("Image loaded successfully (%s, %s KB)", mediaType, sizeKB)
					}
				}
			}

			// Emit tool output body unconditionally (full, untruncated).
			// The CLI layer handles truncation and display filtering.
			if resultContent != "" && !strings.HasPrefix(resultContent, "Image loaded") {
				if a.outputCallback != nil {
					a.outputCallback(resultContent, toolBlock.ID)
				}
			}

			toolResults = append(toolResults, providers.ContentBlock{
				Type:      "tool_result",
				ToolUseID: toolBlock.ID,
				Content:   resultContent,
				IsError:   isError,
			})
		}

		// If we loaded any images, add them to the tool results
		if len(pendingImages) > 0 {
			toolResults = append(toolResults, pendingImages...)
		}

		// Add tool results to history
		a.history = append(a.history, providers.Message{
			Role:    "user",
			Content: toolResults,
		})
	}
}

// GetHistory returns the conversation history
func (a *Agent) GetHistory() []providers.Message {
	return a.history
}

// SetHistory replaces the conversation history with the provided messages.
// Used by session resume to restore a previous conversation state.
func (a *Agent) SetHistory(history []providers.Message) {
	a.history = history
}
